parameters:
  heliopsis_ezforms.controller.class: Heliopsis\eZFormsBundle\Controller\FormController

  heliopsis_ezforms.facade.default.class: Heliopsis\eZFormsBundle\FormFacade\DefaultFormFacade
  heliopsis_ezforms.handlers.multiplexer.class: Heliopsis\eZFormsBundle\FormHandler\MultiplexerHandler
  heliopsis_ezforms.handlers.null.class: Heliopsis\eZFormsBundle\FormHandler\NullHandler

  heliopsis_ezforms.form_provider.content_remoteid_map.class: Heliopsis\eZFormsBundle\Provider\Form\ContentRemoteIdMap
  heliopsis_ezforms.form_provider.content_type_identifier_map.class: Heliopsis\eZFormsBundle\Provider\Form\ContentTypeIdentifierMap
  heliopsis_ezforms.form_provider.chain.class: Heliopsis\eZFormsBundle\Provider\Form\Chain

  heliopsis_ezforms.handler_provider.single_handler.class: Heliopsis\eZFormsBundle\Provider\Handler\SingleHandlerProvider
  heliopsis_ezforms.handler_provider.content_remoteid_map.class: Heliopsis\eZFormsBundle\Provider\Handler\ContentRemoteIdMap
  heliopsis_ezforms.handler_provider.content_type_identifier_map.class: Heliopsis\eZFormsBundle\Provider\Handler\ContentTypeIdentifierMap
  heliopsis_ezforms.handler_provider.chain.class: Heliopsis\eZFormsBundle\Provider\Handler\Chain

  heliopsis_ezforms.response_provider.redirect_confirm.class: Heliopsis\eZFormsBundle\Provider\Response\RedirectToConfirmViewResponseProvider
  heliopsis_ezforms.response_provider.redirect_confirm.view_type: confirm

  # Deprecated: use %heliopsis_ezforms.handlers.multiplexer.class% instead
  heliopsis_ezforms.handlers.chain.class: %heliopsis_ezforms.handlers.multiplexer.class%

services:

  # synthetic services are really defined in DependencyInjection\Compiler\ServiceAliasesPass
  heliopsis_ezforms.facade:
    synthetic: true

  heliopsis_ezforms.form_provider:
    synthetic: true

  heliopsis_ezforms.handler_provider:
    synthetic: true

  heliopsis_ezforms.response_provider:
    synthetic: true

  heliopsis_ezforms.controller:
    class: %heliopsis_ezforms.controller.class%
    calls:
      - [ 'setContainer', [ @service_container ] ]

  heliopsis_ezforms.facade.default:
    class: %heliopsis_ezforms.facade.default.class%
    arguments: [ @heliopsis_ezforms.form_provider, @heliopsis_ezforms.handler_provider, @heliopsis_ezforms.response_provider ]

  heliopsis_ezforms.handlers.null:
    class: %heliopsis_ezforms.handlers.null.class%

  heliopsis_ezforms.response_provider.redirect_confirm:
    class: %heliopsis_ezforms.response_provider.redirect_confirm.class%
    arguments: [@router, %heliopsis_ezforms.response_provider.redirect_confirm.view_type%]

  heliopsis_ezforms.handler_provider.null:
    class: %heliopsis_ezforms.handler_provider.single_handler.class%
    arguments: [ @heliopsis_ezforms.handlers.null ]